spring:
  application:
    name: investment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_service
    username: joyeeun
    password: dPdmsdk?0928
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka