spring:
  application:
    name: investment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_service
    username: joyeeun
    password: dPdmsdk?0928
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: host.docker.internal
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  client:
    config:
      loan-group-service:
        url: ${LOAN_GROUP_SERVICE_URL:http://host.docker.internal:8084}
      invest-service:
        url: ${INVEST_SERVICE_URL:http://host.docker.internal:8081}
      repayment-service:
        url: ${REPAYMENT_SERVICE_URL:http://host.docker.internal:8082}
      loan-service:
        url: ${LOAN_SERVICE_URL:http://host.docker.internal:8083}
      user-service:
        url: ${USER_SERVICE_URL:http://host.docker.internal:8085}

logging:
  level:
    feign:
      logger: DEBUG